### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by josephtkim** [saas-0326/prj-rev-bwfs-dasmoto#6]
**Grade: Exceeds Expectations**

**Summary:** I think you did a great job with your project implementation, which exceeded expectations. The page design seems to follow the project spec guidelines closely, which is no small feat taking a given outline and creating a working page based on it. In addition, the code was well formatted and structured, making it easily readable. This is a great start to the Intensive Program!

The areas for improvement here are to give each img element an alt attribute to provide descriptions for the images, and to provide a description for each major section your HTML and CSS code to make it easier to quickly identify them for yourself and other developers.

As a further challenge, consider adding responsive design to your page. This might take some extra research, but can be a great way to learn and apply important web design concepts. You can take a look at these resources to get started - http://getbootstrap.com/ and https://css-tricks.com/snippets/css/a-guide-to-flexbox/. Based on your work so far, I think you are up for the challenge. Keep up the great work!

**Comment by saas-0326** [comment]
Thank you very much for the review and feedback on my project, I really liked it, you pointed out some things I hadn't notice and also some tips to do it better.

I would like to learn how to make responsive design since I don't know anything about it, was expecting that unit on the cource, but I'll take your advice and review those links to get started as soon as posible.

Again thank you very much!
